### ISSUE TITLE
Broken "Triggers Getting Started Guide" hyperlink on https://tekton.dev/docs/triggers/install/

### ISSUE THREAD

**Issue by firmsoil** [tektoncd/website#126]
# Expected Behavior
[Triggers Getting Started Guide](https://tekton.dev/docs/triggers/getting-started/README) hyperlink on https://tekton.dev/docs/triggers/install/ should return valid webpage content.

# Actual Behavior
[Triggers Getting Started Guide](https://tekton.dev/docs/triggers/getting-started/README) hyperlink on https://tekton.dev/docs/triggers/install/ returns 

Not found
Oops! This page doesn't exist. Try going back to our home page.

# Steps to Reproduce the Problem
Navigate to https://tekton.dev/docs/triggers/install/ and select [Triggers Getting Started Guide](https://tekton.dev/docs/triggers/getting-started/README) hyperlink.

**Comment by AlanGreene** [comment]
This will take a little more work than I initially expected. Keeping the links working both in the GitHub markdown file and on the website is tricky, I thought I had it working but was using the wrong branch when testing on GitHub.

On the website, URLs are transformed so that a markdown file is represented as a folder in the URL path, i.e. `my-file.md` becomes `my-file/` (assuming the name is not modified in the sync config). This means that relative links in markdown files end up breaking.

In the case of the install page linking to the getting started guide we have:
- a link in `install.md` pointing to `./getting-started/`

When deployed on the website we end up with:
- a relative link on `.../install/` which will resolve to `.../install/getting-started/` which is wrong
- we're expecting the resolved URL to be `.../getting-started/`

There may be tools in a newer version of Hugo (v0.62+) that could help, see [Markdown render hooks](https://gohugo.io/getting-started/configuration-markup/#markdown-render-hooks). From the release notes:
> This version brings Markdown Render Hooks. This gives you full control over how links and images in Markdown are rendered without using any shortcodes. With this, **you can get Markdown links that work on both GitHub and Hugo**

Unassigning myself for now as I don't have time to dive deeper into this at the moment. I'll try to pick it up again soon if someone else doesn't get there before me.

/unassign

**Comment by popcor255** [comment]
fixed #181 

/close

**Comment by AlanGreene** [comment]
Looks like this is still broken, and was broken even before #185 was merged.
Before #185 it landed on a 404 page on the website, now it lands on a 404 page in the Triggers repo on GitHub.

/reopen

**Comment by AlanGreene** [comment]
Fixed by https://github.com/tektoncd/website/pull/187
/close
